# == Class: transmission::settings
#
class transmission::settings (
  $group                          = $transmission::group,
  $user                           = $transmission::user,
  $configfile                     = $transmission::configfile,
  $service_enable                 = $transmission::service_enable,
  $service_name                   = $transmission::service_name,
  $alt_speed_down                 = $transmission::alt_speed_down,
  $alt_speed_enabled              = $transmission::alt_speed_enabled,
  $alt_speed_time_begin           = $transmission::alt_speed_time_begin,
  $alt_speed_time_day             = $transmission::alt_speed_time_day,
  $alt_speed_time_enabled         = $transmission::alt_speed_time_enabled,
  $alt_speed_time_end             = $transmission::alt_speed_time_end,
  $alt_speed_up                   = $transmission::alt_speed_up,
  $bind_address_ipv4              = $transmission::bind_address_ipv4,
  $bind_address_ipv6              = $transmission::bind_address_ipv6,
  $blocklist_enabled              = $transmission::blocklist_enabled,
  $blocklist_url                  = $transmission::blocklist_url,
  $cache_size_mb                  = $transmission::cache_size_mb,
  $dht_enabled                    = $transmission::dht_enabled,
  $download_dir                   = $transmission::download_dir,
  $download_queue_enabled         = $transmission::download_queue_enabled,
  $download_queue_size            = $transmission::download_queue_size,
  $encryption                     = $transmission::encryption,
  $idle_seeding_limit             = $transmission::idle_seeding_limit,
  $idle_seeding_limit_enabled     = $transmission::idle_seeding_limit_enabled,
  $incomplete_dir                 = $transmission::incomplete_dir,
  $incomplete_dir_enabled         = $transmission::incomplete_dir_enabled,
  $lpd_enabled                    = $transmission::lpd_enabled,
  $message_level                  = $transmission::message_level,
  $peer_congestion_algorithm      = $transmission::peer_congestion_algorithm,
  $peer_id_ttl_hours              = $transmission::peer_id_ttl_hours,
  $peer_limit_global              = $transmission::peer_limit_global,
  $peer_limit_per_torrent         = $transmission::peer_limit_per_torrent,
  $peer_port                      = $transmission::peer_port,
  $peer_port_random_high          = $transmission::peer_port_random_high,
  $peer_port_random_low           = $transmission::peer_port_random_low,
  $peer_port_random_on_start      = $transmission::peer_port_random_on_start,
  $peer_socket_tos                = $transmission::peer_socket_tos,
  $pex_enabled                    = $transmission::pex_enabled,
  $port_forwarding_enabled        = $transmission::port_forwarding_enabled,
  $preallocation                  = $transmission::preallocation,
  $prefetch_enabled               = $transmission::prefetch_enabled,
  $queue_stalled_enabled          = $transmission::queue_stalled_enabled,
  $queue_stalled_minutes          = $transmission::queue_stalled_minutes,
  $ratio_limit                    = $transmission::ratio_limit,
  $ratio_limit_enabled            = $transmission::ratio_limit_enabled,
  $rename_partial_files           = $transmission::rename_partial_files,
  $rpc_authentication_required    = $transmission::rpc_authentication_required,
  $rpc_bind_address               = $transmission::rpc_bind_address,
  $rpc_enabled                    = $transmission::rpc_enabled,
  $rpc_host_whitelist             = $transmission::rpc_host_whitelist,
  $rpc_host_whitelist_enabled     = $transmission::rpc_host_whitelist_enabled,
  $rpc_password                   = $transmission::rpc_password,
  $rpc_port                       = $transmission::rpc_port,
  $rpc_url                        = $transmission::rpc_url,
  $rpc_username                   = $transmission::rpc_username,
  $rpc_whitelist                  = $transmission::rpc_whitelist,
  $rpc_whitelist_enabled          = $transmission::rpc_whitelist_enabled,
  $scrape_paused_torrents_enabled = $transmission::scrape_paused_torrents_enabled,
  $script_torrent_done_enabled    = $transmission::script_torrent_done_enabled,
  $script_torrent_done_filename   = $transmission::script_torrent_done_filename,
  $seed_queue_enabled             = $transmission::seed_queue_enabled,
  $seed_queue_size                = $transmission::seed_queue_size,
  $speed_limit_down               = $transmission::speed_limit_down,
  $speed_limit_down_enabled       = $transmission::speed_limit_down_enabled,
  $speed_limit_up                 = $transmission::speed_limit_up,
  $speed_limit_up_enabled         = $transmission::speed_limit_up_enabled,
  $start_added_torrents           = $transmission::start_added_torrents,
  $trash_original_torrent_files   = $transmission::trash_original_torrent_files,
  $umask                          = $transmission::umask,
  $upload_slots_per_torrent       = $transmission::upload_slots_per_torrent,
  $utp_enabled                    = $transmission::utp_enabled,
) {
  if $download_dir != $incomplete_dir {
    file { [ $download_dir, $incomplete_dir ]:
      ensure => directory,
      owner  => $user,
      group  => $group,
    }
  }

  transition { "stop ${service_name} service":
    resource   => Service[$service_name],
    attributes => { ensure => stopped },
    prior_to   => File[$configfile],
  }
  
  file { $configfile:
    ensure  => file,
    content => template('transmission/settings.json.erb'),
    notify  => Service[$service_name],
  }
}
